export const TOGGLE_ORIGIN_MODAL = 'TOGGLE_ORIGIN_MODAL';
export const TOGGLE_DESTINATION_MODAL = 'TOGGLE_DESTINATION_MODAL';
export const CHANGE_PASSENGERS_NUMBER = 'CHANGE_PASSENGERS_NUMBER';
export const TOGGLE_ROUND_TRIP = 'TOGGLE_ROUND_TRIP';

