export const SET_ORIGIN_POINT = 'SET_ORIGIN_POINT'
export const SET_DESTINATION_POINT = 'SET_DESTINATION_POINT'
export const CHANGE_PASSENGERS_NUMBER = 'CHANGE_PASSENGERS_NUMBER'
export const TOGGLE_ROUND_TRIP = 'TOGGLE_ROUND_TRIP'
export const SET_STARTDATE = 'SET_STARTDATE'
export const SET_ENDDATE = 'SET_ENDDATE'
export const SET_ORIGINTRIP_ID = 'SET_ORIGINTRIP_ID'
export const SET_RETURNTRIP_ID = 'SET_RETURNTRIP_ID'


